import type {
  ApprovedTemplate,
  Campaign,
  CampaignDraft,
  ImportScenarioState,
  InboundAsset,
  Lead,
  LeadOwner,
  LeadSegment,
  SegmentDraft,
} from "@/lib/acquisition/types";
import { getSegmentLeadIds } from "@/lib/acquisition/helpers";

const note = (id: string, author: string, content: string, createdAt: string) => ({ id, author, content, createdAt });
const activity = (
  id: string,
  type: "ingest" | "validation" | "assignment" | "crm" | "campaign" | "note",
  title: string,
  description: string,
  createdAt: string,
) => ({ id, type, title, description, createdAt });

const lead = (record: Omit<Lead, "fullName"> & { fullName?: string }): Lead => ({
  ...record,
  fullName: record.fullName ?? `${record.firstName} ${record.lastName}`,
});

export const acquisitionOwners: LeadOwner[] = [
  { id: "owner-1", name: "Camila Rojas", title: "Inbound advisor", load: 11, focus: "Meta + formularios" },
  { id: "owner-2", name: "Diego Leon", title: "Revenue advisor", load: 8, focus: "Landing + CRM" },
  { id: "owner-3", name: "Valeria Soto", title: "Outbound advisor", load: 7, focus: "Prospeccion IA" },
];

export const leadEvolutionSeries = [
  { day: "03 Mar", captured: 6, validated: 3, ready: 2 },
  { day: "05 Mar", captured: 8, validated: 5, ready: 3 },
  { day: "07 Mar", captured: 10, validated: 7, ready: 4 },
  { day: "09 Mar", captured: 9, validated: 6, ready: 3 },
  { day: "11 Mar", captured: 12, validated: 8, ready: 5 },
  { day: "13 Mar", captured: 14, validated: 10, ready: 7 },
  { day: "14 Mar", captured: 11, validated: 9, ready: 6 },
];

export const acquisitionLeadsMock: Lead[] = [
  lead({
    id: "lead-001",
    firstName: "Mariana",
    lastName: "Vega",
    company: "Luma Skin Lab",
    jobTitle: "Founder",
    industry: "Beauty",
    country: "Peru",
    city: "Lima",
    whatsapp: "+51 987 441 209",
    phone: "+51 987 441 209",
    email: "mariana@lumaskinlab.pe",
    instagram: "@lumaskinlab",
    website: "lumaskinlab.pe",
    linkedin: "linkedin.com/in/marianavega",
    source: "form",
    interest: "Quiere estructurar captacion para pedidos desde Instagram.",
    productInterest: "Ventra Capture + WhatsApp activation",
    budgetRange: "$1.5k - $3k / mes",
    score: 92,
    priority: "high",
    status: "ready_to_contact",
    ownerId: "owner-1",
    ownerName: "Camila Rojas",
    tags: ["Meta Ads", "Retail", "High intent"],
    notes: [
      note("note-001", "Camila Rojas", "Pidio velocidad de respuesta menor a 10 minutos.", "2026-03-14T08:20:00.000Z"),
      note("note-002", "Camila Rojas", "Acepta trabajar solo con leads con opt-in comprobable.", "2026-03-14T08:36:00.000Z"),
    ],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-14T08:11:00.000Z",
    whatsappOptInSource: "Checkout form",
    whatsappOptInProof: "Checkbox marketing con IP y timestamp.",
    hasValidWhatsapp: true,
    validationState: "validated",
    validationSummary: "Telefono, email y dominio verificados.",
    whatsappState: "valid",
    lastContactAt: "2026-03-14T09:02:00.000Z",
    createdAt: "2026-03-14T08:08:00.000Z",
    updatedAt: "2026-03-14T09:02:00.000Z",
    activities: [
      activity("activity-001", "ingest", "Lead captado desde formulario premium", "Entro desde el formulario de rutina facial completa.", "2026-03-14T08:08:00.000Z"),
      activity("activity-002", "validation", "Validacion automatica completada", "Se confirmo numero con WhatsApp y email corporativo.", "2026-03-14T08:12:00.000Z"),
      activity("activity-003", "assignment", "Asignado a Camila Rojas", "Lead enviado al owner con SLA de 15 minutos.", "2026-03-14T08:15:00.000Z"),
    ],
  }),
  lead({
    id: "lead-002",
    firstName: "Diego",
    lastName: "Salvatierra",
    company: "Ruta Norte Logistics",
    jobTitle: "Commercial lead",
    industry: "Logistics",
    country: "Chile",
    city: "Santiago",
    whatsapp: "+56 9 7812 0041",
    phone: "+56 2 2811 0041",
    email: "diego.salvatierra@rutanorte.cl",
    instagram: "@rutanortelogistics",
    website: "rutanorte.cl",
    linkedin: "linkedin.com/in/diegosalvatierra",
    source: "landing",
    interest: "Busca ordenar las entradas de cotizacion de transporte B2B.",
    productInterest: "Lead intake orchestration",
    budgetRange: "$3k - $5k / mes",
    score: 88,
    priority: "high",
    status: "qualified",
    ownerId: "owner-2",
    ownerName: "Diego Leon",
    tags: ["B2B", "Landing", "Ops"],
    notes: [note("note-003", "Diego Leon", "Pide CRM con trazabilidad por ejecutivo.", "2026-03-13T19:15:00.000Z")],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-13T18:58:00.000Z",
    whatsappOptInSource: "Landing principal",
    whatsappOptInProof: "Consent text aceptado antes de enviar solicitud.",
    hasValidWhatsapp: true,
    validationState: "validated",
    validationSummary: "Datos completos, empresa y cargo verificados.",
    whatsappState: "valid",
    lastContactAt: "2026-03-14T07:40:00.000Z",
    createdAt: "2026-03-13T18:55:00.000Z",
    updatedAt: "2026-03-14T07:40:00.000Z",
    sentToCrmAt: "2026-03-14T07:42:00.000Z",
    activities: [
      activity("activity-004", "ingest", "Solicitud recibida desde landing", "Completo una pagina de cotizacion para transporte recurrente.", "2026-03-13T18:55:00.000Z"),
      activity("activity-005", "crm", "Lead enviado al CRM", "Se creo ficha para seguimiento del equipo de ventas.", "2026-03-14T07:42:00.000Z"),
    ],
  }),
  lead({
    id: "lead-003",
    firstName: "Valeria",
    lastName: "Quispe",
    company: "Nuna Travel House",
    jobTitle: "Growth manager",
    industry: "Travel",
    country: "Peru",
    city: "Cusco",
    whatsapp: "",
    phone: "+51 84 221 918",
    email: "valeria@nuna.travel",
    instagram: "@nunatravelhouse",
    website: "nuna.travel",
    linkedin: "linkedin.com/in/valeriaquispe",
    source: "widget",
    interest: "Necesita captacion desde el sitio sin perder leads nocturnos.",
    productInterest: "Widget + routing to CRM",
    budgetRange: "$1k - $2k / mes",
    score: 66,
    priority: "medium",
    status: "pending_validation",
    ownerId: "owner-1",
    ownerName: "Camila Rojas",
    tags: ["Widget", "Travel", "Sin WhatsApp"],
    notes: [note("note-004", "Camila Rojas", "Falta numero movil con WhatsApp para activar contacto.", "2026-03-14T06:38:00.000Z")],
    whatsappOptIn: false,
    hasValidWhatsapp: false,
    validationState: "review",
    validationSummary: "Email correcto, pero sin numero movil confirmable.",
    whatsappState: "missing",
    createdAt: "2026-03-14T06:30:00.000Z",
    updatedAt: "2026-03-14T06:38:00.000Z",
    activities: [
      activity("activity-006", "ingest", "Lead captado desde widget sticky", "Consulta por automatizar reservas y seguimiento.", "2026-03-14T06:30:00.000Z"),
      activity("activity-007", "validation", "Validacion parcial", "Se detuvo por falta de WhatsApp valido.", "2026-03-14T06:38:00.000Z"),
    ],
  }),
  lead({
    id: "lead-004",
    firstName: "Sergio",
    lastName: "Paredes",
    company: "Mercado Kilo",
    jobTitle: "COO",
    industry: "Ecommerce",
    country: "Colombia",
    city: "Bogota",
    whatsapp: "+57 315 883 1942",
    phone: "+57 601 883 1942",
    email: "sergio.paredes@mercadokilo.co",
    instagram: "@mercadokilo",
    website: "mercadokilo.co",
    linkedin: "linkedin.com/in/sergioparedes",
    source: "csv",
    interest: "Importo base de interesados del ultimo pop-up de descuento.",
    productInterest: "CSV ingestion + validation layer",
    budgetRange: "$2k - $4k / mes",
    score: 54,
    priority: "low",
    status: "duplicate",
    ownerId: "owner-2",
    ownerName: "Diego Leon",
    tags: ["CSV", "Duplicate", "Retail"],
    notes: [note("note-005", "Diego Leon", "Existe un lead previo con mismo email y mismo numero.", "2026-03-13T16:12:00.000Z")],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-12T11:02:00.000Z",
    whatsappOptInSource: "Export from popup campaign",
    whatsappOptInProof: "Campo consent_status=accepted en CSV.",
    hasValidWhatsapp: true,
    validationState: "review",
    validationSummary: "El dato es usable, pero ya existe registro previo.",
    whatsappState: "valid",
    createdAt: "2026-03-13T16:05:00.000Z",
    updatedAt: "2026-03-13T16:12:00.000Z",
    duplicateOfLeadId: "lead-010",
    activities: [
      activity("activity-008", "ingest", "Importado por CSV", "Archivo de registro de popup promocional.", "2026-03-13T16:05:00.000Z"),
      activity("activity-009", "validation", "Duplicado detectado", "Coincide con email y telefono de otro lead activo.", "2026-03-13T16:12:00.000Z"),
    ],
  }),
  lead({
    id: "lead-005",
    firstName: "Camila",
    lastName: "Torres",
    company: "Atlas Cargo Tech",
    jobTitle: "Head of sales",
    industry: "SaaS",
    country: "Mexico",
    city: "Monterrey",
    whatsapp: "+52 81 1414 6605",
    phone: "+52 81 1414 6605",
    email: "camila@atlascargo.tech",
    instagram: "@atlascargotech",
    website: "atlascargo.tech",
    linkedin: "linkedin.com/in/camilatorres",
    source: "manual",
    interest: "Quiere captacion estructurada para demos comerciales enterprise.",
    productInterest: "Lead scoring + CRM handoff",
    budgetRange: "$4k - $7k / mes",
    score: 95,
    priority: "high",
    status: "qualified",
    ownerId: "owner-2",
    ownerName: "Diego Leon",
    tags: ["Enterprise", "Manual", "Board priority"],
    notes: [note("note-006", "Diego Leon", "Fundadores esperan demo esta semana.", "2026-03-12T15:20:00.000Z")],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-12T15:05:00.000Z",
    whatsappOptInSource: "Sales discovery call",
    whatsappOptInProof: "Confirmacion grabada en discovery.",
    hasValidWhatsapp: true,
    validationState: "validated",
    validationSummary: "Lead enriquecido manualmente con dominio y cargo real.",
    whatsappState: "valid",
    lastContactAt: "2026-03-14T08:48:00.000Z",
    createdAt: "2026-03-12T15:00:00.000Z",
    updatedAt: "2026-03-14T08:48:00.000Z",
    sentToCrmAt: "2026-03-12T16:02:00.000Z",
    activities: [
      activity("activity-010", "assignment", "Lead creado manualmente", "Ingresado tras referral del equipo fundador.", "2026-03-12T15:00:00.000Z"),
      activity("activity-011", "crm", "Handoff al CRM completado", "Se abrio etapa discovery enterprise.", "2026-03-12T16:02:00.000Z"),
    ],
  }),
  lead({
    id: "lead-006",
    firstName: "Andres",
    lastName: "Ponce",
    company: "Cafe Distrito",
    jobTitle: "Owner",
    industry: "Restaurants",
    country: "Peru",
    city: "Arequipa",
    whatsapp: "+51 970 774 112",
    phone: "+51 970 774 112",
    email: "hola@cafedistrito.pe",
    instagram: "@cafedistrito.pe",
    website: "cafedistrito.pe",
    linkedin: "linkedin.com/in/andresponce",
    source: "ai_prospecting",
    interest: "Prospeccion detecto tickets altos y expansion a delivery premium.",
    productInterest: "Prospection to WhatsApp activation",
    budgetRange: "$900 - $1.8k / mes",
    score: 74,
    priority: "medium",
    status: "pending_validation",
    ownerId: "owner-3",
    ownerName: "Valeria Soto",
    tags: ["IA", "Hospitality", "No opt-in"],
    notes: [note("note-007", "Valeria Soto", "Se necesita consentimiento antes de contacto por plantilla.", "2026-03-13T13:02:00.000Z")],
    whatsappOptIn: false,
    hasValidWhatsapp: true,
    validationState: "review",
    validationSummary: "Numero valido, pero solo hay fuente publica y sin consentimiento.",
    whatsappState: "needs_opt_in",
    createdAt: "2026-03-13T12:50:00.000Z",
    updatedAt: "2026-03-13T13:02:00.000Z",
    activities: [
      activity("activity-012", "ingest", "Detectado por Prospeccion IA", "Business con senal de compra por expansion reciente.", "2026-03-13T12:50:00.000Z"),
      activity("activity-013", "validation", "Bloqueado para campana", "Falta opt-in confirmado para WhatsApp.", "2026-03-13T13:02:00.000Z"),
    ],
  }),
  lead({
    id: "lead-007",
    firstName: "Lucia",
    lastName: "Herrera",
    company: "Casa Nube Home",
    jobTitle: "Ecommerce manager",
    industry: "Ecommerce",
    country: "Chile",
    city: "Valparaiso",
    whatsapp: "+56 9 6451 9930",
    phone: "+56 9 6451 9930",
    email: "lucia@casanubehome.cl",
    instagram: "@casanubehome",
    website: "casanubehome.cl",
    linkedin: "linkedin.com/in/luciaherrera",
    source: "campaign",
    interest: "Llego desde secuencia de remarketing con alta intencion de recompra.",
    productInterest: "Capture + contact campaign",
    budgetRange: "$1.2k - $2.2k / mes",
    score: 83,
    priority: "high",
    status: "contacted",
    ownerId: "owner-1",
    ownerName: "Camila Rojas",
    tags: ["Remarketing", "Decor", "Warm"],
    notes: [note("note-008", "Camila Rojas", "Respondio a la primera plantilla y pidio propuesta.", "2026-03-14T07:52:00.000Z")],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-13T10:12:00.000Z",
    whatsappOptInSource: "Meta lead ad",
    whatsappOptInProof: "Opt-in registrado en formulario instantaneo.",
    hasValidWhatsapp: true,
    validationState: "validated",
    validationSummary: "Lead apto, se activo seguimiento comercial.",
    whatsappState: "valid",
    lastContactAt: "2026-03-14T07:50:00.000Z",
    createdAt: "2026-03-13T10:12:00.000Z",
    updatedAt: "2026-03-14T07:52:00.000Z",
    activities: [
      activity("activity-014", "campaign", "Primera plantilla enviada", "Se uso plantilla aprobada de seguimiento comercial.", "2026-03-14T07:50:00.000Z"),
      activity("activity-015", "note", "Respondio interes", "Solicita propuesta adaptada a 2 sucursales.", "2026-03-14T07:52:00.000Z"),
    ],
  }),
  lead({
    id: "lead-008",
    firstName: "Mateo",
    lastName: "Rojas",
    company: "Alegra Dental",
    jobTitle: "Clinic director",
    industry: "Health",
    country: "Peru",
    city: "Trujillo",
    whatsapp: "+51 944 515 731",
    phone: "+51 944 515 731",
    email: "mateo@alegradental.pe",
    instagram: "@alegradental",
    website: "alegradental.pe",
    linkedin: "linkedin.com/in/mateorojas",
    source: "landing",
    interest: "Busca unificar leads de formulario, landing y recepcion digital.",
    productInterest: "Inbound orchestration",
    budgetRange: "$1.8k - $3.2k / mes",
    score: 87,
    priority: "high",
    status: "ready_to_contact",
    ownerId: "owner-2",
    ownerName: "Diego Leon",
    tags: ["Health", "Landing", "Multi-branch"],
    notes: [note("note-009", "Diego Leon", "Hay presupuesto y urgencia por responder mas rapido.", "2026-03-13T21:11:00.000Z")],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-13T20:58:00.000Z",
    whatsappOptInSource: "Lead magnet landing",
    whatsappOptInProof: "Timestamp + source campaign_id present.",
    hasValidWhatsapp: true,
    validationState: "validated",
    validationSummary: "Datos consistentes y sin duplicidades.",
    whatsappState: "valid",
    createdAt: "2026-03-13T20:56:00.000Z",
    updatedAt: "2026-03-13T21:11:00.000Z",
    activities: [
      activity("activity-016", "ingest", "Lead de landing clinica", "Solicito diagnostico para gestion comercial.", "2026-03-13T20:56:00.000Z"),
      activity("activity-017", "validation", "Listo para activar", "Quedo apto para contacto por plantilla aprobada.", "2026-03-13T21:11:00.000Z"),
    ],
  }),
  lead({
    id: "lead-009",
    firstName: "Renata",
    lastName: "Castillo",
    company: "Bento Fit",
    jobTitle: "Growth lead",
    industry: "Food",
    country: "Mexico",
    city: "CDMX",
    whatsapp: "+52 55 4512 7791",
    phone: "+52 55 4512 7791",
    email: "renata@bentofit.mx",
    instagram: "@bentofitmx",
    website: "bentofit.mx",
    linkedin: "linkedin.com/in/renatacastillo",
    source: "form",
    interest: "Evaluando automatizar captacion para suscripciones semanales.",
    productInterest: "Lead capture stack",
    budgetRange: "$1k - $1.6k / mes",
    score: 72,
    priority: "medium",
    status: "new",
    ownerId: "owner-1",
    ownerName: "Camila Rojas",
    tags: ["Subscription", "Food", "Fresh lead"],
    notes: [],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-14T05:22:00.000Z",
    whatsappOptInSource: "Primary form",
    whatsappOptInProof: "Checkbox accepted on submit.",
    hasValidWhatsapp: true,
    validationState: "validated",
    validationSummary: "Lead nuevo y completo, aun no asignado a secuencia.",
    whatsappState: "valid",
    createdAt: "2026-03-14T05:22:00.000Z",
    updatedAt: "2026-03-14T05:22:00.000Z",
    activities: [activity("activity-018", "ingest", "Lead nuevo desde formulario", "Completo solicitud de asesoramiento comercial.", "2026-03-14T05:22:00.000Z")],
  }),
  lead({
    id: "lead-010",
    firstName: "Bruno",
    lastName: "Alvarado",
    company: "Nodo Legal",
    jobTitle: "Partner",
    industry: "Legal",
    country: "Peru",
    city: "Lima",
    whatsapp: "+51 932 104 580",
    phone: "+51 932 104 580",
    email: "bruno@nodolegal.pe",
    instagram: "@nodolegal",
    website: "nodolegal.pe",
    linkedin: "linkedin.com/in/brunoalvarado",
    source: "widget",
    interest: "Buscaba solo informacion general, sin urgencia ni fit comercial.",
    productInterest: "Widget qualification",
    budgetRange: "Menos de $500 / mes",
    score: 34,
    priority: "low",
    status: "discarded",
    ownerId: "owner-1",
    ownerName: "Camila Rojas",
    tags: ["Low fit", "Widget"],
    notes: [note("note-010", "Camila Rojas", "Sin presupuesto ni equipo para implementar pronto.", "2026-03-12T11:42:00.000Z")],
    whatsappOptIn: false,
    hasValidWhatsapp: true,
    validationState: "review",
    validationSummary: "Datos correctos, pero sin fit comercial actual.",
    whatsappState: "needs_opt_in",
    createdAt: "2026-03-12T11:30:00.000Z",
    updatedAt: "2026-03-12T11:42:00.000Z",
    activities: [
      activity("activity-019", "ingest", "Consulta inbound de baja prioridad", "Solicito informacion sin una necesidad concreta.", "2026-03-12T11:30:00.000Z"),
      activity("activity-020", "note", "Lead descartado", "Se marca para no activar campanas.", "2026-03-12T11:42:00.000Z"),
    ],
  }),
  lead({
    id: "lead-011",
    firstName: "Fernanda",
    lastName: "Silva",
    company: "Orbe Studio",
    jobTitle: "Creative director",
    industry: "Agencies",
    country: "Argentina",
    city: "Cordoba",
    whatsapp: "+54 9 351 778 0404",
    phone: "+54 9 351 778 0404",
    email: "fernanda@orbestudio.ar",
    instagram: "@orbestudio",
    website: "orbestudio.ar",
    linkedin: "linkedin.com/in/fernandasilva",
    source: "csv",
    interest: "Importo leads del evento de lanzamiento de marca.",
    productInterest: "CSV cleanup + segmentation",
    budgetRange: "$1k - $2k / mes",
    score: 79,
    priority: "medium",
    status: "ready_to_contact",
    ownerId: "owner-2",
    ownerName: "Diego Leon",
    tags: ["CSV", "Agency", "Opt-in"],
    notes: [note("note-011", "Diego Leon", "Base importada con buen nivel de datos y permiso.", "2026-03-13T09:20:00.000Z")],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-11T18:20:00.000Z",
    whatsappOptInSource: "Event registration CSV",
    whatsappOptInProof: "Columna opt_in_whatsapp=true mas timestamp.",
    hasValidWhatsapp: true,
    validationState: "validated",
    validationSummary: "CSV limpio, sin errores y con consentimiento.",
    whatsappState: "valid",
    createdAt: "2026-03-13T09:02:00.000Z",
    updatedAt: "2026-03-13T09:20:00.000Z",
    activities: [
      activity("activity-021", "ingest", "Base importada desde evento", "Se cargaron contactos del workshop de branding.", "2026-03-13T09:02:00.000Z"),
      activity("activity-022", "validation", "Lead listo para contacto", "La fila quedo normalizada y usable.", "2026-03-13T09:20:00.000Z"),
    ],
  }),
  lead({
    id: "lead-012",
    firstName: "Paula",
    lastName: "Navarro",
    company: "Grid Solar Works",
    jobTitle: "Commercial manager",
    industry: "Energy",
    country: "Colombia",
    city: "Medellin",
    whatsapp: "+57 313 552 8841",
    phone: "+57 313 552 8841",
    email: "paula.navarro@gridsolar.co",
    instagram: "@gridsolarworks",
    website: "gridsolar.co",
    linkedin: "linkedin.com/in/paulanavarro",
    source: "ai_prospecting",
    interest: "Prospeccion priorizo expansion regional y alto ticket.",
    productInterest: "Prospection + CRM routing",
    budgetRange: "$4k - $6k / mes",
    score: 90,
    priority: "high",
    status: "qualified",
    ownerId: "owner-3",
    ownerName: "Valeria Soto",
    tags: ["IA", "Energy", "High value"],
    notes: [note("note-012", "Valeria Soto", "Ya acepto demo por correo y paso a CRM.", "2026-03-14T06:10:00.000Z")],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-13T14:11:00.000Z",
    whatsappOptInSource: "Outbound qualification call",
    whatsappOptInProof: "Consentimiento registrado por asesor.",
    hasValidWhatsapp: true,
    validationState: "validated",
    validationSummary: "Cuenta enriquecida y lista para seguimiento enterprise.",
    whatsappState: "valid",
    createdAt: "2026-03-13T13:50:00.000Z",
    updatedAt: "2026-03-14T06:10:00.000Z",
    sentToCrmAt: "2026-03-14T06:12:00.000Z",
    activities: [
      activity("activity-023", "ingest", "Cuenta detectada por IA", "Aparece con apertura de expansion regional.", "2026-03-13T13:50:00.000Z"),
      activity("activity-024", "crm", "Movida a CRM", "Se asigno seguimiento enterprise con alta prioridad.", "2026-03-14T06:12:00.000Z"),
    ],
  }),
  lead({
    id: "lead-013",
    firstName: "Esteban",
    lastName: "Cueva",
    company: "Pausa Cowork",
    jobTitle: "Founder",
    industry: "Real Estate",
    country: "Peru",
    city: "Lima",
    whatsapp: "+51 923 550 841",
    phone: "+51 923 550 841",
    email: "esteban@pausacowork.pe",
    instagram: "@pausacowork",
    website: "pausacowork.pe",
    linkedin: "linkedin.com/in/estebancueva",
    source: "manual",
    interest: "Quiere capturar leads para membresias corporativas.",
    productInterest: "Forms + CRM",
    budgetRange: "$900 - $1.4k / mes",
    score: 68,
    priority: "medium",
    status: "new",
    ownerId: "owner-2",
    ownerName: "Diego Leon",
    tags: ["Manual", "Real estate"],
    notes: [],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-14T04:10:00.000Z",
    whatsappOptInSource: "Networking lunch",
    whatsappOptInProof: "Consentimiento verbal confirmado por asesor.",
    hasValidWhatsapp: true,
    validationState: "validated",
    validationSummary: "Listo para triage inicial.",
    whatsappState: "valid",
    createdAt: "2026-03-14T04:10:00.000Z",
    updatedAt: "2026-03-14T04:10:00.000Z",
    activities: [activity("activity-025", "assignment", "Lead agregado manualmente", "Ingreso luego de reunion comercial.", "2026-03-14T04:10:00.000Z")],
  }),
  lead({
    id: "lead-014",
    firstName: "Jimena",
    lastName: "Prado",
    company: "Punto Cacao",
    jobTitle: "Marketing lead",
    industry: "Food",
    country: "Ecuador",
    city: "Quito",
    whatsapp: "+593 99 122 7711",
    phone: "+593 99 122 7711",
    email: "jimena@puntocacao.ec",
    instagram: "@puntocacao",
    website: "puntocacao.ec",
    linkedin: "linkedin.com/in/jimenaprado",
    source: "landing",
    interest: "Quiere mejorar tiempos de respuesta de franquicias.",
    productInterest: "Lead validation + campaigns",
    budgetRange: "$1.4k - $2.5k / mes",
    score: 64,
    priority: "medium",
    status: "pending_validation",
    ownerId: "owner-1",
    ownerName: "Camila Rojas",
    tags: ["Landing", "Food", "Review"],
    notes: [note("note-013", "Camila Rojas", "Email dominio correcto, falta confirmar opt-in.", "2026-03-14T03:55:00.000Z")],
    whatsappOptIn: false,
    hasValidWhatsapp: true,
    validationState: "review",
    validationSummary: "Numero existe, pero consentimiento pendiente.",
    whatsappState: "needs_opt_in",
    createdAt: "2026-03-14T03:42:00.000Z",
    updatedAt: "2026-03-14T03:55:00.000Z",
    activities: [
      activity("activity-026", "ingest", "Lead nuevo de landing", "Formulario enviado desde pagina de franquicias.", "2026-03-14T03:42:00.000Z"),
      activity("activity-027", "validation", "Pendiente de opt-in", "No puede entrar a campana hasta completar permiso.", "2026-03-14T03:55:00.000Z"),
    ],
  }),
  lead({
    id: "lead-015",
    firstName: "Rodrigo",
    lastName: "Leon",
    company: "Volta Bikes",
    jobTitle: "Growth director",
    industry: "Mobility",
    country: "Chile",
    city: "Santiago",
    whatsapp: "+56 9 9212 5540",
    phone: "+56 9 9212 5540",
    email: "rodrigo@voltabikes.cl",
    instagram: "@voltabikes",
    website: "voltabikes.cl",
    linkedin: "linkedin.com/in/rodrigoleon",
    source: "campaign",
    interest: "Respondio a oferta de demo y quiere activar base de test rides.",
    productInterest: "Controlled WhatsApp campaigns",
    budgetRange: "$2k - $3.8k / mes",
    score: 84,
    priority: "high",
    status: "contacted",
    ownerId: "owner-3",
    ownerName: "Valeria Soto",
    tags: ["Campaign", "Mobility", "Warm"],
    notes: [note("note-014", "Valeria Soto", "Pidio secuencia gradual por sedes.", "2026-03-13T17:31:00.000Z")],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-13T17:00:00.000Z",
    whatsappOptInSource: "Ad instant form",
    whatsappOptInProof: "Lead ad with consent checkbox.",
    hasValidWhatsapp: true,
    validationState: "validated",
    validationSummary: "Listo para campana controlada por lotes.",
    whatsappState: "valid",
    lastContactAt: "2026-03-14T08:02:00.000Z",
    createdAt: "2026-03-13T17:00:00.000Z",
    updatedAt: "2026-03-14T08:02:00.000Z",
    activities: [
      activity("activity-028", "campaign", "Primer contacto enviado", "Se programo mensaje comercial de prueba.", "2026-03-14T08:02:00.000Z"),
      activity("activity-029", "note", "Interes en piloto", "Quiere iniciar con 100 leads maximo.", "2026-03-14T08:07:00.000Z"),
    ],
  }),
  lead({
    id: "lead-016",
    firstName: "Daniela",
    lastName: "Costa",
    company: "Marea Boutique",
    jobTitle: "Owner",
    industry: "Fashion",
    country: "Peru",
    city: "Piura",
    whatsapp: "+51 945 771 030",
    phone: "+51 945 771 030",
    email: "daniela@mareaboutique.pe",
    instagram: "@mareaboutique",
    website: "mareaboutique.pe",
    linkedin: "linkedin.com/in/danielacosta",
    source: "form",
    interest: "Necesita captar leads para relanzamiento de nueva coleccion.",
    productInterest: "Capture + segments + campaign prep",
    budgetRange: "$1.2k - $2k / mes",
    score: 86,
    priority: "high",
    status: "ready_to_contact",
    ownerId: "owner-1",
    ownerName: "Camila Rojas",
    tags: ["Fashion", "Form", "Launch"],
    notes: [note("note-015", "Camila Rojas", "Quiere secuencia con mensaje de lanzamiento y cupos limitados.", "2026-03-14T02:35:00.000Z")],
    whatsappOptIn: true,
    whatsappOptInAt: "2026-03-14T02:20:00.000Z",
    whatsappOptInSource: "Collection waitlist form",
    whatsappOptInProof: "Lead magnet checkbox + timestamp.",
    hasValidWhatsapp: true,
    validationState: "validated",
    validationSummary: "Lead apto y listo para activacion comercial.",
    whatsappState: "valid",
    createdAt: "2026-03-14T02:18:00.000Z",
    updatedAt: "2026-03-14T02:35:00.000Z",
    activities: [
      activity("activity-030", "ingest", "Lead captado por waitlist", "Formulario de relanzamiento de coleccion.", "2026-03-14T02:18:00.000Z"),
      activity("activity-031", "validation", "Validado para WhatsApp", "Numero y consentimiento confirmados.", "2026-03-14T02:35:00.000Z"),
    ],
  }),
];

export const acquisitionSegmentsMock: LeadSegment[] = [
  {
    id: "segment-001",
    name: "Leads nuevos de Meta Ads",
    description: "Captura fresca con primera respuesta pendiente.",
    intent: "Priorizar triage de demanda de alto ritmo.",
    ruleSummary: ["Fuente form", "Estado nuevo", "Opt-in confirmado"],
    rules: { source: "form", status: "new", industry: "all", optIn: "confirmed", onlyValidWhatsapp: true },
    leadIds: getSegmentLeadIds(acquisitionLeadsMock, { source: "form", status: "new", industry: "all", optIn: "confirmed", onlyValidWhatsapp: true }),
    whatsappEligibleCount: 1,
    lastUpdated: "2026-03-14T08:18:00.000Z",
  },
  {
    id: "segment-002",
    name: "Leads con WhatsApp valido",
    description: "Base lista para workflows de contacto controlado.",
    intent: "Detectar volumen util para campanas aprobadas.",
    ruleSummary: ["WhatsApp valido", "Cualquier fuente", "Sin descartados"],
    rules: { source: "all", status: "all", industry: "all", optIn: "all", onlyValidWhatsapp: true },
    leadIds: getSegmentLeadIds(acquisitionLeadsMock.filter((item) => item.status !== "discarded"), { source: "all", status: "all", industry: "all", optIn: "all", onlyValidWhatsapp: true }),
    whatsappEligibleCount: acquisitionLeadsMock.filter((item) => item.hasValidWhatsapp && item.status !== "discarded").length,
    lastUpdated: "2026-03-14T08:30:00.000Z",
  },
  {
    id: "segment-003",
    name: "Leads con opt-in confirmado",
    description: "Solo registros aptos para usar plantillas aprobadas.",
    intent: "Evitar activar contactos sin permiso.",
    ruleSummary: ["Opt-in confirmado", "WhatsApp valido", "Sin duplicados"],
    rules: { source: "all", status: "all", industry: "all", optIn: "confirmed", onlyValidWhatsapp: true },
    leadIds: getSegmentLeadIds(acquisitionLeadsMock.filter((item) => item.status !== "duplicate"), { source: "all", status: "all", industry: "all", optIn: "confirmed", onlyValidWhatsapp: true }),
    whatsappEligibleCount: acquisitionLeadsMock.filter((item) => item.whatsappOptIn && item.hasValidWhatsapp && item.status !== "duplicate").length,
    lastUpdated: "2026-03-14T08:31:00.000Z",
  },
  {
    id: "segment-004",
    name: "Ecommerce caliente",
    description: "Leads de retail digital con score alto y senal de compra.",
    intent: "Preparar activacion comercial para categorias con alta respuesta.",
    ruleSummary: ["Industria Ecommerce", "Ready o contacted", "Opt-in confirmado"],
    rules: { source: "all", status: "ready_to_contact", industry: "Ecommerce", optIn: "confirmed", onlyValidWhatsapp: true },
    leadIds: getSegmentLeadIds(acquisitionLeadsMock, { source: "all", status: "ready_to_contact", industry: "Ecommerce", optIn: "confirmed", onlyValidWhatsapp: true }),
    whatsappEligibleCount: 0,
    lastUpdated: "2026-03-14T08:32:00.000Z",
  },
  {
    id: "segment-005",
    name: "Leads sin respuesta",
    description: "Leads ya tocados que necesitan siguiente empuje comercial.",
    intent: "Mantener continuidad sin blasting indiscriminado.",
    ruleSummary: ["Estado contacted", "Opt-in confirmado", "WhatsApp valido"],
    rules: { source: "all", status: "contacted", industry: "all", optIn: "confirmed", onlyValidWhatsapp: true },
    leadIds: getSegmentLeadIds(acquisitionLeadsMock, { source: "all", status: "contacted", industry: "all", optIn: "confirmed", onlyValidWhatsapp: true }),
    whatsappEligibleCount: 2,
    lastUpdated: "2026-03-14T08:34:00.000Z",
  },
  {
    id: "segment-006",
    name: "Importados por CSV",
    description: "Base lista para limpieza, scoring y handoff.",
    intent: "Controlar calidad de cargas externas.",
    ruleSummary: ["Fuente CSV", "Cualquier estado", "Control de duplicados"],
    rules: { source: "csv", status: "all", industry: "all", optIn: "all", onlyValidWhatsapp: false },
    leadIds: getSegmentLeadIds(acquisitionLeadsMock, { source: "csv", status: "all", industry: "all", optIn: "all", onlyValidWhatsapp: false }),
    whatsappEligibleCount: 2,
    lastUpdated: "2026-03-14T08:40:00.000Z",
  },
];

export const acquisitionAssetsMock: InboundAsset[] = [
  {
    id: "asset-form-01",
    type: "form",
    name: "Demo premium inbound",
    status: "active",
    channel: "Landing principal",
    views: 1840,
    conversions: 114,
    completionRate: 36,
    lastLeadAt: "2026-03-14T08:12:00.000Z",
    previewTitle: "Solicita una auditoria comercial",
    previewDescription: "Formulario de 6 campos para detectar urgencia, canal y volumen de leads actual.",
    fields: ["Nombre", "Empresa", "WhatsApp", "Email", "Volumen mensual", "Opt-in"],
    embedCode: "<script data-ventra-form=\"demo-premium\"></script>",
  },
  {
    id: "asset-form-02",
    type: "form",
    name: "Waitlist coleccion retail",
    status: "active",
    channel: "Micrositio de lanzamiento",
    views: 960,
    conversions: 71,
    completionRate: 42,
    lastLeadAt: "2026-03-14T02:18:00.000Z",
    previewTitle: "Entra primero al lanzamiento",
    previewDescription: "Captura leads para listas de espera con prioridad por ciudad y ticket esperado.",
    fields: ["Nombre", "WhatsApp", "Ciudad", "Categoria", "Opt-in"],
    embedCode: "<script data-ventra-form=\"waitlist-retail\"></script>",
  },
  {
    id: "asset-widget-01",
    type: "widget",
    name: "Widget sticky asesor comercial",
    status: "active",
    channel: "Sitio corporativo",
    views: 2440,
    conversions: 83,
    completionRate: 21,
    lastLeadAt: "2026-03-14T06:30:00.000Z",
    previewTitle: "Habla con un asesor",
    previewDescription: "Widget lateral con CTA discreta para tomar leads sin romper el flujo del sitio.",
    fields: ["Nombre", "WhatsApp", "Empresa", "Necesidad"],
    embedCode: "<script data-ventra-widget=\"advisor-sticky\"></script>",
  },
  {
    id: "asset-widget-02",
    type: "widget",
    name: "Quiz de readiness comercial",
    status: "draft",
    channel: "Blog comparativo",
    views: 620,
    conversions: 18,
    completionRate: 19,
    lastLeadAt: "2026-03-12T22:10:00.000Z",
    previewTitle: "Evalua tu proceso comercial",
    previewDescription: "Microquiz que segmenta leads por madurez y canal prioritario.",
    fields: ["Nombre", "Email", "WhatsApp", "Canal", "Equipo"],
    embedCode: "<script data-ventra-widget=\"readiness-quiz\"></script>",
  },
];

export const approvedTemplatesMock: ApprovedTemplate[] = [
  {
    id: "template-001",
    name: "Demo inbound confirmada",
    category: "demo",
    language: "es_PE",
    variables: ["firstName", "productInterest", "ownerName"],
    preview: "Hola {{firstName}}, vimos tu interes en {{productInterest}}. {{ownerName}} puede ayudarte con el siguiente paso cuando lo prefieras.",
    compliance: "Plantilla aprobada para confirmar interes comercial entrante.",
  },
  {
    id: "template-002",
    name: "Seguimiento con propuesta",
    category: "follow_up",
    language: "es_LATAM",
    variables: ["firstName", "company", "variableValue"],
    preview: "Hola {{firstName}}, preparamos una propuesta inicial para {{company}} enfocada en {{variableValue}}. Si quieres, te comparto el siguiente detalle.",
    compliance: "Usar solo con leads ya validados y con opt-in.",
  },
  {
    id: "template-003",
    name: "Recordatorio de cotizacion",
    category: "quote",
    language: "es_MX",
    variables: ["firstName", "budgetRange", "ownerName"],
    preview: "Hola {{firstName}}, dejamos lista una propuesta alineada a tu rango {{budgetRange}}. {{ownerName}} queda atento para coordinar.",
    compliance: "Aprobada para leads listos para contacto o contacted.",
  },
];

export const acquisitionCampaignsMock: Campaign[] = [
  {
    id: "campaign-001",
    name: "Activacion beauty con demo",
    status: "running",
    audienceSegmentId: "segment-003",
    templateId: "template-001",
    scheduledAt: "2026-03-14T10:00:00.000Z",
    batchLimit: 40,
    sent: 96,
    delivered: 91,
    read: 67,
    responded: 24,
    failed: 5,
    summary: "Secuencia de contacto para leads con opt-in confirmado y urgencia alta.",
  },
  {
    id: "campaign-002",
    name: "Warm leads sin respuesta",
    status: "scheduled",
    audienceSegmentId: "segment-005",
    templateId: "template-002",
    scheduledAt: "2026-03-14T15:30:00.000Z",
    batchLimit: 25,
    sent: 0,
    delivered: 0,
    read: 0,
    responded: 0,
    failed: 0,
    summary: "Reactivacion controlada sobre leads ya tocados y con interes vigente.",
  },
  {
    id: "campaign-003",
    name: "CSV cleanup premium",
    status: "completed",
    audienceSegmentId: "segment-006",
    templateId: "template-003",
    scheduledAt: "2026-03-13T11:00:00.000Z",
    batchLimit: 20,
    sent: 34,
    delivered: 32,
    read: 25,
    responded: 9,
    failed: 2,
    summary: "Uso de base importada ya normalizada con limites por lote y plantilla aprobada.",
  },
];

export const importScenarioStatesMock: ImportScenarioState[] = [
  {
    id: "empty",
    fileName: "Sin archivo",
    uploadedAt: "2026-03-14T09:10:00.000Z",
    rowsDetected: 0,
    readyToImport: 0,
    warnings: 0,
    errors: 0,
    duplicates: 0,
    summary: "Arrastra un CSV o usa una muestra para validar columnas y detectar duplicados antes de importar.",
    mappings: [],
    previewRows: [],
  },
  {
    id: "uploading",
    fileName: "meta-leads-marzo.csv",
    uploadedAt: "2026-03-14T09:12:00.000Z",
    rowsDetected: 248,
    readyToImport: 0,
    warnings: 0,
    errors: 0,
    duplicates: 0,
    summary: "Leyendo encabezados, normalizando numeros y comparando emails contra la base actual.",
    mappings: [
      { csvColumn: "first_name", field: "nombre", status: "mapped" },
      { csvColumn: "last_name", field: "apellido", status: "mapped" },
      { csvColumn: "mobile_number", field: "whatsapp", status: "mapped" },
    ],
    previewRows: [],
  },
  {
    id: "preview",
    fileName: "meta-leads-marzo.csv",
    uploadedAt: "2026-03-14T09:14:00.000Z",
    rowsDetected: 248,
    readyToImport: 232,
    warnings: 8,
    errors: 4,
    duplicates: 4,
    summary: "El archivo se puede importar. Revisa las pocas filas con warnings antes de confirmar.",
    mappings: [
      { csvColumn: "first_name", field: "nombre", status: "mapped" },
      { csvColumn: "last_name", field: "apellido", status: "mapped" },
      { csvColumn: "company_name", field: "empresa", status: "mapped" },
      { csvColumn: "sector", field: "industria", status: "mapped" },
      { csvColumn: "mobile_number", field: "whatsapp", status: "mapped" },
      { csvColumn: "mail", field: "email", status: "mapped" },
      { csvColumn: "optin_wa", field: "opt-in whatsapp", status: "mapped" },
      { csvColumn: "ig_handle", field: "instagram", status: "optional" },
    ],
    previewRows: [
      { rowNumber: 4, firstName: "Andrea", lastName: "Pico", company: "Casa Verde", industry: "Home", whatsapp: "+51 955 801 220", email: "andrea@casaverde.pe", source: "csv", optInWhatsapp: "yes", validation: "valid" },
      { rowNumber: 5, firstName: "Fabio", lastName: "Marin", company: "Kite Mobility", industry: "Mobility", whatsapp: "+57 318 199 0034", email: "fabio@kitemobility.co", source: "csv", optInWhatsapp: "yes", validation: "warning", issue: "Falta ciudad" },
      { rowNumber: 6, firstName: "Elena", lastName: "Suarez", company: "Milo Dental", industry: "Health", whatsapp: "987001", email: "elena@milodental.pe", source: "csv", optInWhatsapp: "yes", validation: "error", issue: "WhatsApp invalido" },
      { rowNumber: 7, firstName: "Julio", lastName: "Barrera", company: "Bruna Bags", industry: "Fashion", whatsapp: "+56 9 8122 0041", email: "julio@brunabags.cl", source: "csv", optInWhatsapp: "yes", validation: "duplicate", issue: "Email ya existe" },
    ],
  },
  {
    id: "warning",
    fileName: "landing-q1-export.csv",
    uploadedAt: "2026-03-14T09:16:00.000Z",
    rowsDetected: 84,
    readyToImport: 62,
    warnings: 18,
    errors: 0,
    duplicates: 4,
    summary: "El archivo no trae columna de industria ni ciudad. Puedes importar, pero perderas segmentacion inicial.",
    mappings: [
      { csvColumn: "full_name", field: "nombre", status: "mapped" },
      { csvColumn: "company", field: "empresa", status: "mapped" },
      { csvColumn: "phone", field: "whatsapp", status: "mapped" },
      { csvColumn: "-", field: "industria", status: "missing" },
      { csvColumn: "-", field: "ciudad", status: "missing" },
      { csvColumn: "email", field: "email", status: "mapped" },
    ],
    previewRows: [
      { rowNumber: 3, firstName: "Lia", lastName: "Paredes", company: "Domo Fit", industry: "-", whatsapp: "+51 989 411 205", email: "lia@domofit.pe", source: "csv", optInWhatsapp: "yes", validation: "warning", issue: "Sin industria" },
      { rowNumber: 4, firstName: "Noah", lastName: "Rios", company: "Rook Media", industry: "-", whatsapp: "+57 313 990 0122", email: "noah@rookmedia.co", source: "csv", optInWhatsapp: "yes", validation: "warning", issue: "Sin ciudad" },
    ],
  },
  {
    id: "error",
    fileName: "form-export-broken.csv",
    uploadedAt: "2026-03-14T09:18:00.000Z",
    rowsDetected: 41,
    readyToImport: 21,
    warnings: 5,
    errors: 15,
    duplicates: 0,
    summary: "Hay demasiadas filas con telefono incompleto y emails sin formato. Conviene corregir antes de importar.",
    mappings: [
      { csvColumn: "name", field: "nombre", status: "mapped" },
      { csvColumn: "email_address", field: "email", status: "mapped" },
      { csvColumn: "mobile", field: "whatsapp", status: "mapped" },
      { csvColumn: "consent", field: "opt-in whatsapp", status: "mapped" },
    ],
    previewRows: [
      { rowNumber: 8, firstName: "Rosa", lastName: "Mena", company: "Studio Flow", industry: "Agencies", whatsapp: "1234", email: "rosa@studioflow", source: "csv", optInWhatsapp: "yes", validation: "error", issue: "Telefono y email invalidos" },
      { rowNumber: 9, firstName: "Kevin", lastName: "Tineo", company: "Moto Lab", industry: "Mobility", whatsapp: "", email: "kevin@motolab.pe", source: "csv", optInWhatsapp: "no", validation: "error", issue: "Sin numero de contacto" },
    ],
  },
  {
    id: "duplicates",
    fileName: "expo-commerce.csv",
    uploadedAt: "2026-03-14T09:21:00.000Z",
    rowsDetected: 126,
    readyToImport: 103,
    warnings: 3,
    errors: 2,
    duplicates: 18,
    summary: "Se encontraron 18 contactos ya existentes. Puedes consolidarlos o importarlos como nuevas versiones.",
    mappings: [
      { csvColumn: "nombre", field: "nombre", status: "mapped" },
      { csvColumn: "apellido", field: "apellido", status: "mapped" },
      { csvColumn: "empresa", field: "empresa", status: "mapped" },
      { csvColumn: "movil", field: "whatsapp", status: "mapped" },
      { csvColumn: "correo", field: "email", status: "mapped" },
    ],
    previewRows: [
      { rowNumber: 11, firstName: "Fernanda", lastName: "Silva", company: "Orbe Studio", industry: "Agencies", whatsapp: "+54 9 351 778 0404", email: "fernanda@orbestudio.ar", source: "csv", optInWhatsapp: "yes", validation: "duplicate", issue: "Mismo email y mismo numero" },
      { rowNumber: 14, firstName: "Sergio", lastName: "Paredes", company: "Mercado Kilo", industry: "Ecommerce", whatsapp: "+57 315 883 1942", email: "sergio.paredes@mercadokilo.co", source: "csv", optInWhatsapp: "yes", validation: "duplicate", issue: "Registro previo activo" },
    ],
  },
  {
    id: "success",
    fileName: "expo-commerce.csv",
    uploadedAt: "2026-03-14T09:26:00.000Z",
    rowsDetected: 126,
    readyToImport: 103,
    warnings: 3,
    errors: 2,
    duplicates: 18,
    summary: "Importacion completada. Los leads validos ya aparecen clasificados para triage, CRM o campanas controladas.",
    mappings: [
      { csvColumn: "nombre", field: "nombre", status: "mapped" },
      { csvColumn: "apellido", field: "apellido", status: "mapped" },
      { csvColumn: "empresa", field: "empresa", status: "mapped" },
      { csvColumn: "movil", field: "whatsapp", status: "mapped" },
      { csvColumn: "correo", field: "email", status: "mapped" },
    ],
    previewRows: [
      { rowNumber: 21, firstName: "Andrea", lastName: "Pico", company: "Casa Verde", industry: "Home", whatsapp: "+51 955 801 220", email: "andrea@casaverde.pe", source: "csv", optInWhatsapp: "yes", validation: "valid" },
      { rowNumber: 22, firstName: "Marco", lastName: "Lara", company: "Cima Bikes", industry: "Mobility", whatsapp: "+56 9 8812 4410", email: "marco@cimabikes.cl", source: "csv", optInWhatsapp: "yes", validation: "valid" },
    ],
  },
];
export const defaultSegmentDraft: SegmentDraft = {
  name: "Leads listos por activar",
  description: "Audiencia dinamica para validar y accionar leads con senal comercial.",
  rules: { source: "all", status: "ready_to_contact", industry: "all", optIn: "confirmed", onlyValidWhatsapp: true },
};

export const defaultCampaignDraft: CampaignDraft = {
  name: "Activacion controlada marzo",
  segmentId: "segment-003",
  templateId: "template-001",
  variableValue: "demostracion guiada",
  schedule: "2026-03-14T18:00:00.000Z",
  batchLimit: 35,
};
